name: Integration tests

on:
  push:
    branches:
    - '*'
    tags:
    - '*'
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: m2-payments

      - name: Install dependencies
        uses: shivammathur/setup-php@master
        with:
          php-version: '7.3'
          extension: intl, mbstring, json, bcmath, sodium, zip
          coverage: xdebug
          tools: composer, php-cs-fixer, phpunit:7.5.19, phpcpd, phpmd

      - name: Install tools
        run: |
          cd $GITHUB_WORKSPACE/m2-payments
          composer global require squizlabs/php_codesniffer
          composer global require magento/magento-coding-standard
          composer global require phpmd/phpmd
          composer global require sebastian/phpcpd

      - name: Run PHPCS inspection
        run: |
          cd $GITHUB_WORKSPACE/m2-payments
          php phpcs --config-set installed_paths ~/.composer/vendor/magento/magento-coding-standard/Magento2
          #php phpcpd ./
          #php phpmd ./ text cleancode,codesize,controversial,design,naming,unusedcode --exclude vendor/
          #php phpcs --standard=PSR1 ./ --ignore=./vendor/*
          php phpcs --runtime-set ignore_warnings_on_exit 1 --standard=PSR2 ./ --ignore=./vendor/*
          php phpcs --runtime-set ignore_warnings_on_exit 1 --standard=~/.composer/vendor/magento/magento-coding-standard/Magento2/ruleset.xml --extensions=php,phtml ./  --ignore=./vendor/*